apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: d68r44nqr-python
  janus-idp.io/tekton: d68r44nqr-python
  backstage.io/kubernetes-id: d68r44nqr-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: d68r44nqr-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
