apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: d68r44nqr-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d68r44nqr-python 
  name: d68r44nqr-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: d68r44nqr-python
    weight: 100 
